### PR TITLE
Laser emitters can be at 45-degree angles

### PR DESCRIPTION
**Pull request by Gaming32**

### CODE REVIEW

**Comment by Gaming32** [comment]
I only considered this "Minecraft-y" enough to work on because signs can have arbitrary non-axis-aligned rotations. Even more than this, in fact.

**Comment by Cart3r1234** [comment]
> I only considered this "Minecraft-y" enough to work on because signs can have arbitrary non-axis-aligned rotations. Even more than this, in fact.

The only blocks that can be placed at 45 and/or 22.5 degree rotation steps in vanilla are less than a full block in size and use entity models (signs, banners, and mob heads).  The last time a unique (aka not counting new sign and mob head types) block that has this property was added was 1.8

**Comment by Gaming32** [comment]
I still think this opens up so many possibilities for making test chambers, regardless of if it has precedent in Vanilla or not. Actually, most of this mod doesn't particularly fit in Vanilla tbh.

**Comment by Gaming32** [comment]
Here's a demonstration of what can be done with this change: https://youtu.be/ERjttYv2Gzs

**Comment by Gaming32** [comment]
Please don't delete the branch though

**Pull request closed without merging**
