### PR TITLE
Make the facades have no collision.

### PR DESCRIPTION
**Pull request by woodiertexas**

### CODE REVIEW

**Comment by Gaming32** [comment]
Actually, the goal of SimpleMultiSidedBlock is to simply create a subclass class of MultifaceBlock with boilerplate implemented sensibly. Consequently, this code shouldn't go in this file, and its presence in this file completely breaks all gels other than conversion gel.

**Comment by Gaming32** [comment]
And don't ignore Checkstyle.

**Comment by woodiertexas** [comment]
> And don't ignore Checkstyle.

If you're going to tell someone to "not ignore checkstyle", actually tell them what to fix.

**Comment by Gaming32** [comment]
The Checkstyle errors are comprehensive enough. But I guess I can paste them here.

```
[ant:checkstyle] [WARN] /home/runner/work/Portal-Cubed/Portal-Cubed/src/main/java/com/fusionflux/portalcubed/blocks/SimpleMultiSidedBlock.java:12: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [WARN] /home/runner/work/Portal-Cubed/Portal-Cubed/src/main/java/com/fusionflux/portalcubed/blocks/SimpleMultiSidedBlock.java:16: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
[ant:checkstyle] [WARN] /home/runner/work/Portal-Cubed/Portal-Cubed/src/main/java/com/fusionflux/portalcubed/blocks/SimpleMultiSidedBlock.java:19:1: Line contains a tab character. [FileTabCharacter]
```

**Comment by woodiertexas** [comment]
> The Checkstyle errors are comprehensive enough. But I guess I can paste them here.
> 
> ```
> [ant:checkstyle] [WARN] /home/runner/work/Portal-Cubed/Portal-Cubed/src/main/java/com/fusionflux/portalcubed/blocks/SimpleMultiSidedBlock.java:12: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
> [40](https://github.com/Fusion-Flux/Portal-Cubed/actions/runs/4537614841/jobs/7995674954?pr=114#step:5:41)
> [ant:checkstyle] [WARN] /home/runner/work/Portal-Cubed/Portal-Cubed/src/main/java/com/fusionflux/portalcubed/blocks/SimpleMultiSidedBlock.java:16: Line matches the illegal pattern 'Trailing whitespace'. [Regexp]
> [41](https://github.com/Fusion-Flux/Portal-Cubed/actions/runs/4537614841/jobs/7995674954?pr=114#step:5:42)
> [ant:checkstyle] [WARN] /home/runner/work/Portal-Cubed/Portal-Cubed/src/main/java/com/fusionflux/portalcubed/blocks/SimpleMultiSidedBlock.java:19:1: Line contains a tab character. [FileTabCharacter]
> ```

Also, I did this in my web browser, not intelliJ

**Pull request closed without merging**
